[package]
name = "obkv-table-client-rs"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdb@service.alipay.com>"]
edition = "2018"

[lib]
name = "obkv"

[[bench]]
name = "concurrent_insert"
harness = false
path = "benches/concurrent_insert/mod.rs"

[dependencies]
byteorder = "1.2"
bytes = "0.4"
chrono = "0.4"
crossbeam = "0.7"
fasthash = "0.4.0"
futures = "0.1.17"
futures-cpupool = "0.1"
lazy_static = "1.3.0"
log = "0.4"
mysql = "16.1.0"
net2 = "0.2"
prometheus = "0.7"
quick-error = "1.2"
r2d2 = "0.8.3"
rand = "0.6"
reqwest = "0.9.18"
rust-crypto = "^0.2"
scheduled-thread-pool = "0.2.0"
serde = "1.0.81"
serde_bytes = "0.10.4"
serde_derive = "1.0.81"
serde_json = "1.0.34"
spin = "0.5.0"
tokio-codec = "0.1"
uuid = "0.7"
zstd = "0.11"

[dev-dependencies]
scoped_threadpool = "0.1"
serial_test = "0.2"
serial_test_derive = "0.2"
tempfile = "3.0"
time = "0.1.42"
version_test_derive = { path = "components/version_test_derive" }

[workspace]
members = ["components/version_test_derive"]
